name: Terraform Apply
on:
  push:
    branches:
      - main
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: GET CODE
        uses: actions/checkout@v4
      - name: INSTALL TERRAFORM 
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terrafrom Apply
        run: |
          terraform init
          terraform apply -auto-approve

